hostIp: 172.20.150.115

spring:
  redis:
    host: ${hostIp}
    port: 6300
  datasource:
    url: jdbc:mysql://${hostIp}:3300/seckill?useUnicode=true&characterEncoding=UTF-8&zeroDateTimestampBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-init-sql: set names utf8mb4


#myabtis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*
  configuration:
    cache-enabled: true
    #log-impl: org.apache.ibatis.logging.commons.JakartaCommonsLoggingImpl
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  tomcat:
    threads:
      max: 500
